name: CI
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fixture:
          - cplusplus
          - schema-cplusplus
          - kotlin
          - schema-kotlin
          - kotlin-jackson
          - schema-kotlin-jackson
          - graphql
          - java
          - schema-java
          - schema-json-csharp
          - typescript
          - schema-typescript
          - javascript
          - schema-javascript
          - flow
          - schema-flow
          - json-ts-csharp
          - python
          - schema-python
          - swift
          - schema-swift
          - rust
          - schema-rust
          - elm
          - schema-elm
          - dart
          - schema-dart
          - csharp
          - schema-csharp
          - ruby
          - schema-ruby
          - golang
          - schema-golang
          - pike
          - schema-pike
          - haskell
          - schema-haskell
          - javascript-prop-types
    name: ${{ matrix.fixture }} tests
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: dart-lang/setup-dart@v1
      with:
        sdk: 2.10.5
    - uses: fwilhe2/setup-kotlin@0.2.0
    - uses: haskell/actions/setup@v1
      with:
        enable-stack: true
    - uses: jorelali/setup-elm@v3
    - uses: ruby/setup-ruby@v1

    - run: sudo apt install -y libboost-all-dev pike8.0-full

    - run: npm install
    - run: pip3.6 install mypy python-dateutil
    - run: gem install bundler:1.16.1
    - run: FIXTURE=${{ matrix.fixture }} npm test
